### ISSUE TITLE
Quick question, has anyone gotten paired up?

### ISSUE THREAD

**Issue by DanielTakeshi** [sdhull/strategic_voting#14]
Now that it's October, I'm wondering if anyone has gotten paired up by the website to do vote swapping.

If so, it might be useful to put a notice on the website to give a status update (I didn't see any).

Thanks!

**Comment by sdhull** [comment]
Hi Daniel!

We haven't begun matching people yet, however I intend to begin that process today!

Unfortunately by my estimation, we don't have enough participants yet to have much of an impact, so please continue help spreading the word.

**Comment by DanielTakeshi** [comment]
OK, thanks for the update. Darn, the main issue is getting all the third party supporters in the swing states on board. I know many safe-state voters who'd be happy to help.

**Comment by sdhull** [comment]
Registrations have (surprisingly) been fairly even, with nearly 50-50 split between 3rd party supporters & Hillary supporters. I don't have state-by-state breakdown yet but that's coming soon...

We just need everyone who has registered to share & encourage friends & family to sign up. Even if we don't find a match for a safe-state voter, if they share it, it increases the odds of more signups which in turn increases the odds of a good match.

**Comment by DanielTakeshi** [comment]
I'll try to ask others to join. 

I don't know how much of this will be possible, but will there be contact information (e.g., emails) among the paired voters? Otherwise some way of validating the integrity of the pairing would be nice, but this would need to get around a few "guidelines/laws" (I think showing a picture of your vote can be illegal).

**Comment by sdhull** [comment]
Update: today I got data & backend ready to do matching. Upon further inspection of the data, it looks like a full half of registered 3rd-party supporters are voting in uncontested states, so (as we guessed) there is indeed a lopsided distribution of users (more Hillary voters in uncontested states).

Matching from here is easy enough, but I still need to build an email template to let people know they've been matched. I'll probably get to that tomorrow.

---

We've talked a bit about "validating". It's legal to take a picture of your ballot in some states, and illegal in others.

From my view, participants are bound by common goals: defeat Trump, support 3rd parties. These goals are furthered by following through with the trade, so it's in everyone's best interest to do so. It's something we're doing "in good faith" and expect others to do the same. As such, I'm not _too_ worried about the validation aspect. That said, I think it would be "cool" to offer the capability of uploading a picture of your vote to the site, maybe just to keep private or share only with your matched voter. In terms of priority though, this isn't high on my list.

As for contact information of your match, I don't intend to share that, however I think I will build an anonymized relay so you can send messages back and forth (though I'm a bit concerned about the possibility for abuse and I might limit the messages you can send to a set of canned messages, similar to how Nintendo limited "chat" in Mario Kart 8). However I'm on the fence about limiting messages, maybe it will simply be anonymized email relay.
