### ISSUE TITLE
Can I help?

### ISSUE THREAD

**Issue by erose** [sdhull/strategic_voting#20]
Hi! I believe I used this site in 2016 — makeminecount.org ?

I'm a web developer with startup experience and would be interested in helping an effort like this for this year's election.

It looks like this project is not still active. Are there any plans to revive it? Or do you know of any efforts to do a similar thing again this year? I looked over projects from https://en.wikipedia.org/wiki/Vote_pairing_in_the_2016_United_States_presidential_election and it seems like Trump Traders is no longer active.

**Comment by sdhull** [comment]
Hello @erose sorry about the late response. You are correct, this was the codebase for makeminecount.org.

I had not planned to revive this. Frankly I'm not feeling super motivated or hopeful that something like this could work this time.

If you'd like to spearhead such an effort I'm happy to help where I can. You can (of course) feel free to use the code from this repo, however I think it's pretty outdated by now. I no longer own that domain so you'd need to figure that part out.

**Comment by erose** [comment]
Thanks @sdhull. I'm not in a position to spearhead work on this, but I'd be excited to contribute. You don't know of anyone else doing a similar project, do you?
