### ISSUE TITLE
Is the email system working?

### ISSUE THREAD

**Issue by DanielTakeshi** [sdhull/strategic_voting#4]
Just curious if the email confirmation is working. I asked to get an email confirmation to my email but didn't get one (for a few days) so I tried a second time, but it didn't work. (OS is Mac El Capitan, browser Google Chrome). I'll keep trying a few times but I thought it would be nice if someone could just give a quick test drive on this.

**Comment by DanielTakeshi** [comment]
And just to be clear, it wasn't in the spam folder.

**Comment by timmc** [comment]
Did you use an email address with a `.` in the user portion? I did, and I was wondering if that was the issue.

**Comment by DanielTakeshi** [comment]
No, I used seita@berkeley.edu

There's only a dot after the institution name, which is required.

**Comment by sdhull** [comment]
@DanielTakeshi @timmc thanks for coming here to inquire. I've been having deliverability issues with mailgun, though I haven't checked recently.

To answer your question, it's working well for most people.

Just checked, looks like we're still having awful deliverability. 10% dropped messages. 😞

**Comment by sdhull** [comment]
However, digging deeper, a fair number of these are from email mis-types. I see some "@gamil.com" etc

It's likely that if you resent your confirmation email, it'd arrive fine. In fact:
<img width="892" alt="screen shot 2016-09-18 at 8 11 10 pm" src="https://cloud.githubusercontent.com/assets/50039/18621709/1b7a15ae-7ddc-11e6-9c30-3ce56fea6785.png">

**Comment by sdhull** [comment]
Ohhh interesting. "Domain of sender address does not exist."

Yeah I haven't set up email service for makeminecount yet. I guess I should do that. Sigh.

**Comment by sdhull** [comment]
OK I think it was a misconfiguration on my part. Sorry about that. Looks like some mail servers are pickier than others about receiving email from an address that wasn't configured properly

**Comment by sdhull** [comment]
anyway thanks for the issue report! please lmk if you didn't receive it this time. I resent it for you and verified in the logs that it went through. for now, I'll be closing this issue.

**Comment by DanielTakeshi** [comment]
I got the email confirmation.
